# The purpose of help is to guide users and briefly explain the purpiose of this program
print('---------------------------------------------')
print('Welcome to the Python Hotseat Millionaire Quiz')
print('---------------------------------------------')
print('Here is a quick run down of the program')
print('---------------------------------------------')
print('This program will ask you for your name')
print('It will then ask you if you feel like watching a movie')
print('If so it will then ask if it\'s raning outside')
print('Then it will ask you to input your desired genre')
print('Finally it will give you a movie recommendation, depending on your circumstances')
print('---------------------------------------------')
print('Have fun')
print('---------------------------------------------')