# The purpose of help is to guide users and briefly explain the purpiose of this program
print('---------------------------------------------')
print('Welcome to the Python Hotseat Millionaire Quiz')
print('---------------------------------------------')
print('Here is a quick run down of the program')
print('---------------------------------------------')
print('This program will ask you for your name')
print('It will then ask you a question')
print('You will then be instructed to answer the question by inputting either "A", "B", "C", or "D"')
print('After you have answered the question, it will provide you with feedback (either correct or wrong)')
print('Finally after all the questions have been answered, you will be given a percentage score')
print('If the percentage is equal to 100, you win the grand prize of $1,000,000')
print('If not you will be asked if you would like to attempt the quiz again')
print('---------------------------------------------')
print('Have fun and good luck')
print('---------------------------------------------')